[package]
name = "miditip"
version = "0.1.0"
authors = ["thiolliere <guillaume.thiolliere@opmbx.org>"]

[dependencies]
argparse = "0.2.0"
portmidi = "0.1.0"
common = { path = "../common" }
serde_json = "0.7.0"
